# Options
CC=latex
MAKE=make
Q=@

# Build
all:
	@echo Compiling Latex Files
	$(Q)$(CC) main.tex
	$(Q)$(CC) main.tex

open:
	open main.dvi

clean:
	rm -f *.aux *.dvi *.log *.nav *.out *.pdf *.ps *.snm *.toc *.vrb
